version: "3"
services:
  web:
    build: .
    container_name: express-api
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: standard-api
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5400:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    environment:
      ADMINER_DESIGN: arcs-material
    ports:
      - "8080:8080"
